services:
  web:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    restart: always
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_marketplace
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_marketplace

volumes:
  postgres_data: 